# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
export DEBIAN_FRONTEND=noninteractive

# Configure guest hostname
sudo bash -c 'echo 127.0.1.1 yunohost.yunohost.org yunohost >> /etc/hosts'
sudo hostname yunohost.yunohost.org
sudo bash -c 'echo yunohost.yunohost.org > /etc/hostname'

# Define root password
echo -e "yunohost\nyunohost" | sudo passwd root

# Allow sudo removal (YunoHost use sudo-ldap)
export SUDO_FORCE_REMOVE=yes

# Upgrade guest (done in install script)
sudo apt-get update
sudo apt-get -y --force-yes upgrade
sudo apt-get -y --force-yes dist-upgrade

# Install YunoHost
wget https://raw.githubusercontent.com/YunoHost/install_script/stretch/install_yunohost -q -O /tmp/install_yunohost
sudo bash /tmp/install_yunohost -a -d $1

# Cleanup
sudo apt-get clean -y
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  
  # Debian Jessie with YunoHost unstable (nightly) release
  config.vm.define "jessie-unstable" do |unstable|
    unstable.vm.box = "debian/contrib-jessie64"
    unstable.vm.provision "shell" do |s|
      s.inline = $script
      s.args   = "'unstable'"
    end
    unstable.vm.provider "virtualbox" do |vb|
      vb.vm.network :private_network, ip: "192.168.33.82"
    end
    unstable.vm.provider "lxc" do |lxc|
      lxc.vm.network :private_network, ip: "192.168.33.82", lxc__bridge_name: 'lxcbr0'
    end
  end

  # Debian Stretch with YunoHost unstable (nightly) release
  config.vm.define "stretch-unstable" do |stretch_unstable|
    stretch_unstable.vm.box = "debian/stretch64"
    stretch_unstable.vm.provision "shell" do |s|
      s.inline = $script
      s.args   = "'unstable'"
    end
    stretch_unstable.vm.provider "virtualbox" do |vb|
      vb.vm.network :private_network, ip: "192.168.33.93"
    end
    stretch_unstable.vm.provider "lxc" do |lxc|
      lxc.vm.network :private_network, ip: "192.168.33.93", lxc__bridge_name: 'lxcbr0'
    end
  end

  # Debian Buster with YunoHost unstable (nightly) release
  config.vm.define "buster-unstable" do |buster_unstable|
    buster_unstable.vm.box = "debian/testing64"
    buster_unstable.vm.provision "shell" do |s|
      s.inline = $script
      s.args   = "'unstable'"
    end
    buster_unstable.vm.provider "virtualbox" do |vb|
      vb.vm.network :private_network, ip: "192.168.33.94"
    end
    buster_unstable.vm.provider "lxc" do |lxc|
      lxc.vm.network :private_network, ip: "192.168.33.94", lxc__bridge_name: 'lxcbr0'
    end
  end

end
