# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
export DEBIAN_FRONTEND=noninteractive

# Define root password
echo -e "yunohost\nyunohost" | sudo passwd root

# Upgrade guest (done in install script)
# sudo apt-get update
# sudo apt-get -y --force-yes upgrade
# sudo apt-get -y --force-yes dist-upgrade

# Configure guest hostname
sudo hostname yunohost.yunohost.org
sudo bash -c 'echo yunohost.yunohost.org > /etc/hostname'
sudo bash -c 'echo 127.0.1.1 yunohost.yunohost.org yunohost >> /etc/hosts'

# Install YunoHost
wget https://raw.githubusercontent.com/YunoHost/install_script/master/install_yunohostv2 -q -O /tmp/install_yunohost
sudo bash /tmp/install_yunohost -a -d $1

# Cleanup
sudo apt-get clean -y
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Default folder sharing
  config.vm.synced_folder ".", "/vagrant"
  # Force guest type, because YunoHost /etc/issue can be tuned
  config.vm.guest = :debian
  
  # Debian Jessie with YunoHost stable release
  config.vm.define "stable8", primary: true do |stable8|
    stable8.vm.box = "debian/jessie64"
    stable8.vm.provision "shell" do |s|
      s.inline = $script
      s.args   = "'stable'"
    end
    stable8.vm.network :private_network, ip: "192.168.33.80"
  end

  # Debian Jessie with YunoHost testing release
  config.vm.define "testing8" do |testing8|
    testing8.vm.box = "debian/jessie64"
    testing8.vm.provision "shell" do |s|
      s.inline = $script
      s.args   = "'testing'"
    end
    testing8.vm.network :private_network, ip: "192.168.33.81"
  end

  # Debian Jessie with YunoHost unstable (nightly) release
  config.vm.define "unstable8" do |unstable8|
    unstable8.vm.box = "debian/jessie64"
    unstable8.vm.provision "shell" do |s|
      s.inline = $script
      s.args   = "'unstable'"
    end
    unstable8.vm.network :private_network, ip: "192.168.33.82"
  end
  
  # Debian Wheezy with YunoHost stable release
  config.vm.define "stable7", primary: true do |stable7|
    stable7.vm.box = "debian/wheezy64"
    stable7.vm.provision "shell" do |s|
      s.inline = $script
      s.args   = "'stable'"
    end
    stable7.vm.network :private_network, ip: "192.168.33.70"
  end

  # Debian Wheezy with YunoHost testing release
  config.vm.define "testing7" do |testing7|
    testing7.vm.box = "debian/wheezy64"
    testing7.vm.provision "shell" do |s|
      s.inline = $script
      s.args   = "'testing'"
    end
    testing7.vm.network :private_network, ip: "192.168.33.71"
  end

  # Debian Wheezy with YunoHost unstable (nightly) release
  config.vm.define "unstable7" do |unstable7|
    unstable7.vm.box = "debian/wheezy64"
    unstable7.vm.provision "shell" do |s|
      s.inline = $script
      s.args   = "'unstable'"
    end
    unstable7.vm.network :private_network, ip: "192.168.33.72"
  end
end
